POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName":"Kuldeep",
    "username":"Tripathi",
    "email":"tkuldeep271@gmail.com",
    "password":"kuldeep46",
    "date":"09-01-2022"
}